/**
 * Offline drug-name autocomplete (F1 — backlog decision D4).
 *
 * Data: assets/drug-db.json, generated by scripts/build-drug-db.mjs from an
 * RxTerms monthly release (U.S. National Library of Medicine). ~9.3k display
 * names + strengths + SXDG RxCUI, ~0.6 MB. Loaded lazily on first search so
 * app startup pays nothing; parsed once and kept in memory (~a few MB).
 *
 * v1 scope: the dataset is EN/US-centric (RxTerms). It ASSISTS entry — free
 * text is always allowed — and gives us RxCUI normalization plumbing for the
 * Phase-2 interaction checker. Local ES brand names come later.
 */

/** [displayName, sxdgRxcui, strengths, synonym] — see build-drug-db.mjs. */
type RawEntry = [string, string, string[], string];

export interface DrugSuggestion {
  /** Human-facing display name, e.g. "Ibuprofen (Oral Pill)". */
  name: string;
  /** RxNorm SXDG RxCUI ("" when unknown) — future interaction-checker key. */
  rxcui: string;
  /** Available strengths, e.g. ["200 mg", "400 mg"]. */
  strengths: string[];
}

interface IndexedEntry extends DrugSuggestion {
  /** Normalized haystack: name + synonym, lowercased, accents stripped. */
  norm: string;
}

let index: IndexedEntry[] | null = null;

function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}

function buildIndex(raw: RawEntry[]): IndexedEntry[] {
  return raw.map(([name, rxcui, strengths, synonym]) => ({
    name,
    rxcui,
    strengths,
    norm: normalize(synonym ? `${name} ${synonym}` : name),
  }));
}

function getIndex(): IndexedEntry[] {
  if (!index) {
    // Lazy require so the JSON is only bundled-parsed when first needed.
    const raw = require("../../assets/drug-db.json") as RawEntry[];
    index = buildIndex(raw);
  }
  return index;
}

/** Test seam: inject a small dataset instead of the bundled asset. */
export function _setDatasetForTests(raw: RawEntry[] | null): void {
  index = raw ? buildIndex(raw) : null;
}

/**
 * Searches the drug database. Ranking:
 *   1. name starts with the query
 *   2. any word in the name starts with the query
 *   3. name contains the query
 * Requires ≥ 2 characters; returns at most `limit` results.
 */
export function searchDrugs(query: string, limit = 6): DrugSuggestion[] {
  const q = normalize(query.trim());
  if (q.length < 2) return [];

  const starts: DrugSuggestion[] = [];
  const wordStarts: DrugSuggestion[] = [];
  const contains: DrugSuggestion[] = [];

  for (const e of getIndex()) {
    const i = e.norm.indexOf(q);
    if (i === -1) continue;
    if (i === 0) starts.push(e);
    else if (/[\s(/-]/.test(e.norm[i - 1] ?? "")) wordStarts.push(e);
    else contains.push(e);
    // Early exit once the best bucket alone can fill the limit.
    if (starts.length >= limit) break;
  }

  return [...starts, ...wordStarts, ...contains].slice(0, limit).map(
    ({ name, rxcui, strengths }) => ({ name, rxcui, strengths })
  );
}
