/**
 * Offline NDC → drug lookup (F2 — barcode-scan accelerator).
 *
 * Data: assets/ndc-db.json, generated by scripts/build-ndc-db.mjs from the
 * RxNorm Current Prescribable Content release joined with RxTerms (both NLM).
 * ~108k NDC9 product codes → SXDG RxCUI, delta-encoded to ~0.65 MB. Decoded
 * lazily into a Map on first lookup (only when the user actually scans).
 */

interface NdcDbAsset {
  /** Unique SXDG RxCUIs referenced by index from the ndc9 stream. */
  sxdgs: number[];
  /** "<delta base36>:<sxdg index base36>;..." — NDC9 ascending. */
  ndc9: string;
}

let map: Map<number, string> | null = null;

function getMap(): Map<number, string> {
  if (!map) {
    // Lazy require so the JSON is only bundled-parsed when first needed.
    const asset = require("../../assets/ndc-db.json") as NdcDbAsset;
    map = new Map();
    let acc = 0;
    for (const token of asset.ndc9.split(";")) {
      const sep = token.indexOf(":");
      acc += parseInt(token.slice(0, sep), 36);
      map.set(acc, String(asset.sxdgs[parseInt(token.slice(sep + 1), 36)]));
    }
  }
  return map;
}

/** Test seam: inject a small dataset instead of the bundled asset. */
export function _setNdcDatasetForTests(entries: [number, string][] | null): void {
  map = entries ? new Map(entries) : null;
}

/**
 * Resolves a 9-digit NDC (labeler + product, no package code) to the SXDG
 * RxCUI of the matching drug-db entry, or null when unknown.
 */
export function lookupNdc9(ndc9: string): string | null {
  if (!/^\d{9}$/.test(ndc9)) return null;
  return getMap().get(Number(ndc9)) ?? null;
}
